name: Deploy Frontend on Push

on:
  push:
    branches:
      - amber-test-deploy

jobs:
  deploy:
    runs-on: PiSense-Amber-Deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files to production directory
        run: |
          rsync -av --delete --exclude='node_modules' $GITHUB_WORKSPACE/ /home/amber/PiSense/PiSense_Frontend/

      - name: Install npm dependencies
        working-directory: /home/amber/PiSense/PiSense_Frontend
        run: |
          npm install

      - name: Restart frontend service
        run: |
          sudo systemctl restart pisense-frontend